name: Documentation (PR, build only)

on:
  pull_request:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Select NodeJS version
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Install dependencies
        run: yarn install

      - name: Build documentation
        run: yarn docs:build
