name: Deploy Documentation

on:
  workflow_call:

concurrency:
  group: docs-deploy
  cancel-in-progress: true

permissions:
  contents: write
  pages: write

jobs:
  docs-deploy:
    name: Deploy
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Select NodeJS version
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        env:
          # renovate: datasource=docker depName=node versioning=node
          NODE_VERSION: "20.14.0"
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install

      - name: Build/deploy documentation
        run: yarn docs:publish
