name: QA

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  qa:
    name: Run QA
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Select NodeJS version
        uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install

      # Pre-build QA
      - name: Check constraints
        run: yarn constraints

      # Build
      - name: Build
        run: |
          yarn workspace js-lib build
          yarn workspace node-project build
          yarn workspace web-project build

      # Post-build QA
      - name: Lint ESLint
        run: yarn lint:eslint
      - name: Lint TSC
        run: yarn lint:tsc
